package com.sundown.maplists.models;

/**
 * Created by Sundown on 8/13/2015.
 */
public enum FieldType {
    FIELD_NAME, FIELD_PHONE, FIELD_EMAIL, FIELD_PHOTO, FIELD_TEXT,
    FIELD_NUMBER, FIELD_PRICE, FIELD_DECIMAL, FIELD_DATE, FIELD_TIME,
    FIELD_DROPDOWN,  FIELD_CHECKBOX, FIELD_URL, FIELD_RATING
}
/* FIELD TITLES ARE LOCATED IN STRINGS.XML*/